swagger: '2.0'
info:
  version: 1.0.0
  title: Hanks Api Documents
  contact:
    name: tonykuo
    email: webber.larch@gmail.com
host: '61.228.216.211:8080'
basePath: /hanks-ap
tags:
  - name: 電子柵欄操作
    description: Fence Controller
  - name: 定位操作
    description: Location Controller
  - name: 登入操作
    description: Login Controll
  - name: 手環操作
    description: Ring Controll
paths:
  /v1/user/join:
    post:
      tags:
        - 登入操作
      summary: 新建用戶(待完成)
      description: 新建用戶(待完成)
      operationId: joinUserUsingPOST
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: debug
          in: query
          description: debug flag
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '400':
          description: 待完成
        '401':
          description: 認證失敗
        '500':
          description: INTERNAL SERVICE ERROR
  /v1/user/login:
    post:
      tags:
        - 登入操作
      summary: 登入(待完成)
      description: 登入(待完成)
      operationId: loginUserUsingPOST
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: debug
          in: query
          description: debug flag
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/LoginDTO'
        '400':
          description: 待完成
        '401':
          description: 認證失敗
        '500':
          description: INTERNAL SERVICE ERROR
  '/v1/user/{uid}/ring/{ringSN}/fence':
    get:
      tags:
        - 電子柵欄操作
      summary: '取得柵欄設定與狀態(多筆, 最多5筆)'
      description: get fence data list
      operationId: getFenceListUsingGET
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: uid
          in: path
          description: FETNET_UID
          required: true
          type: string
        - name: ringSN
          in: path
          description: 手環序號
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
    post:
      tags:
        - 電子柵欄操作
      summary: 建立電子柵欄
      description: create fence data
      operationId: addFenceUsingPOST
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - in: body
          name: fenceDTO
          description: fenceDTO
          required: true
          schema:
            $ref: '#/definitions/FenceDTO'
        - name: uid
          in: path
          description: uid
          required: true
          type: string
        - name: ringSN
          in: path
          description: ringSN
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseSuccessDTO'
        '400':
          description: Server Busy(Timeout) or Expired Action
        '401':
          description: 認證失敗
        '500':
          description: INTERNAL SERVICE ERROR
  '/v1/user/{uid}/ring/{ringSN}/fence/{fenceNo}':
    get:
      tags:
        - 電子柵欄操作
      summary: 取得柵欄設定與狀態(單筆)
      description: get fence data
      operationId: getFenceUsingGET
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: uid
          in: path
          description: FETNET_UID
          required: true
          type: string
        - name: ringSN
          in: path
          description: 手環序號
          required: true
          type: string
        - name: fenceNo
          in: path
          description: 電子柵欄編號
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
  '/v1/user/{uid}/ring/{ringSN}/fence/{fenceNo}/delete':
    post:
      tags:
        - 電子柵欄操作
      summary: 刪除柵欄
      description: delete fence data
      operationId: deleteFenceUsingPOST
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: uid
          in: path
          description: FETNET_UID
          required: true
          type: string
        - name: ringSN
          in: path
          description: 手環序號
          required: true
          type: string
        - name: fenceNo
          in: path
          description: 電子柵欄編號
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
  '/v1/user/{uid}/ring/{ringSN}/fence/{fenceNo}/update':
    post:
      tags:
        - 電子柵欄操作
      summary: 更新柵欄設定
      description: update fence data list
      operationId: updateFenceUsingPOST
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - in: body
          name: fdto
          description: fdto
          required: true
          schema:
            $ref: '#/definitions/FenceDTO'
        - name: uid
          in: path
          description: FETNET_UID
          required: true
          type: string
        - name: ringSN
          in: path
          description: 手環序號
          required: true
          type: string
        - name: fenceNo
          in: path
          description: 電子柵欄編號
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
  '/v1/user/{uid}/ring/{ringSN}/location':
    get:
      tags:
        - 定位操作
      summary: 取得過去軌跡資訊
      description: get Location History(待完成)
      operationId: getLocationHistoryUsingGET
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: uid
          in: path
          description: uid
          required: true
          type: string
        - name: ringSN
          in: path
          description: ringSN
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/LocationReportDTO'
        '400':
          description: Server Busy(Timeout) or Expired Action or Not yet received DR
        '401':
          description: 認證失敗
        '500':
          description: INTERNAL SERVICE ERROR
  '/v1/user/{uid}/ring/{ringSN}/profile':
    get:
      tags:
        - 手環操作
      summary: 取得手環資訊
      description: get ring info
      operationId: getRingInfoUsingGET
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: uid
          in: path
          description: uid
          required: true
          type: string
        - name: ringSN
          in: path
          description: ring_sn
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/RingInfoDTO'
        '400':
          description: Server Busy(Timeout) or Expired Action
        '401':
          description: 認證失敗
        '500':
          description: INTERNAL SERVICE ERROR
  '/v1/user/{uid}/ring/{ringSN}/request/activemode/off':
    post:
      tags:
        - 定位操作
      summary: '要求切換主動追蹤:OFF'
      description: stop active mode(待完成)
      operationId: stopActiveModeUsingPOST
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: uid
          in: path
          description: uid
          required: true
          type: string
        - name: ringSN
          in: path
          description: ringSN
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseSuccessDTO'
        '400':
          description: Server Busy(Timeout) or Expired Action or Not yet received DR
        '401':
          description: 認證失敗
        '500':
          description: INTERNAL SERVICE ERROR
  '/v1/user/{uid}/ring/{ringSN}/request/activemode/on':
    post:
      tags:
        - 定位操作
      summary: '要求切換主動追蹤:ON'
      description: start active mode(待完成)
      operationId: startActiveModeUsingPOST
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: uid
          in: path
          description: uid
          required: true
          type: string
        - name: ringSN
          in: path
          description: ringSN
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseSuccessDTO'
        '400':
          description: Server Busy(Timeout) or Expired Action or Not yet received DR
        '401':
          description: 認證失敗
        '500':
          description: INTERNAL SERVICE ERROR
  '/v1/user/{uid}/ring/{ringSN}/request/gps':
    post:
      tags:
        - 定位操作
      summary: 即時定位(只會回一次)
      description: get current position(可供測試)
      operationId: getCurrentPositionUsingPOST
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: uid
          in: path
          description: 使用者ID
          required: true
          type: string
        - name: ringSN
          in: path
          description: 手環序號
          required: true
          type: string
        - name: debug
          in: query
          description: debug flag
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseSuccessDTO'
        '400':
          description: Server Busy(Timeout) or Expired Action or Not yet received DR
        '401':
          description: 認證失敗
        '500':
          description: INTERNAL SERVICE ERROR
definitions:
  FenceDTO:
    type: object
    required:
      - end_time
      - fence_name
      - latitude
      - longitude
      - radius
      - report_rate
      - start_time
    properties:
      fence_name:
        type: string
        example: fence_name
        description: fence_name
      longitude:
        type: number
        format: double
        example: longitude(TODO)
        description: longitude
      latitude:
        type: number
        format: double
        example: latitude(TODO)
        description: latitude
      radius:
        type: integer
        format: int32
        example: radius(TODO)
        description: radius
      report_rate:
        type: integer
        format: int32
        example: 10
        description: '回傳頻率(10,15,60)'
      start_time:
        type: string
        example: '15:00'
        description: start time
      end_time:
        type: string
        example: '18:00'
        description: end time
  LocationReportDTO:
    type: object
    required:
      - data
      - message
    properties:
      data:
        $ref: '#/definitions/LocationReportBody'
      message:
        type: string
        example: success
        description: success
  LoginBody:
    type: object
    required:
      - response_time
      - ring_data
      - user_data
    properties:
      user_data:
        $ref: '#/definitions/UserInfo'
      ring_data:
        $ref: '#/definitions/RingInfo'
      response_time:
        type: string
        format: date-time
        example: '2016-08-25T01:24:22Z'
        description: server response time
  LocationReport:
    type: object
    required:
      - cmd
      - cmd_key
      - latitude
      - longitude
      - record_time
      - ring_response_code
      - ring_sn
      - type
    properties:
      ring_sn:
        type: string
        example: '12345678901'
        description: 手環序號
      cmd:
        type: integer
        format: int32
        example: 1
        description: 手環命令
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
      cmd_key:
        type: string
        example: 待定義
        description: 手環命令PK
      longitude:
        type: number
        format: double
        example: 26.1234
        description: longitude
      latitude:
        type: number
        format: double
        example: 28.5678
        description: latitude
      type:
        type: string
        example: 'gps, rrc_indooc, rrc_outdoor'
        description: 定位資料模式
      ring_response_code:
        type: integer
        format: int32
        description: 定位失敗碼(0為成功 / 1為失敗)
        enum:
          - 0
          - 1
      record_time:
        type: string
        format: date-time
        example: '2016-08-25T15:12:35Z'
        description: 定位資料記錄時間
  ResponseSuccessDTO:
    type: object
    required:
      - data
      - message
    properties:
      data:
        $ref: '#/definitions/ResponseTime'
      message:
        type: string
        example: success
        description: success
  LocationReportBody:
    type: object
    required:
      - location_data
      - response_time
    properties:
      location_data:
        type: array
        items:
          $ref: '#/definitions/LocationReport'
      response_time:
        type: string
        format: date-time
        example: '2016-08-25T01:24:22Z'
        description: server response time
  RingInfoBody:
    type: object
    required:
      - response_time
      - ring_data
    properties:
      ring_data:
        $ref: '#/definitions/RingInfo'
      response_time:
        type: string
        format: date-time
        example: '2016-08-25T01:24:22Z'
        description: server response time
  ResponseTime:
    type: object
    required:
      - response_time
    properties:
      response_time:
        type: string
        format: date-time
        example: '2016-08-25T01:24:22Z'
        description: server response time
  UserInfo:
    type: object
    required:
      - client_id
      - contact_number
      - login_dt
      - nickname
      - owner_uid
    properties:
      owner_uid:
        type: string
        description: UID
      client_id:
        type: string
        example: '12345678901'
        description: client id
      nickname:
        type: string
        description: nickname
      contact_number:
        type: string
        description: 聯略電話
      login_dt:
        type: string
        format: date-time
        example: '2016-08-25T01:12:35Z'
        description: 登入時間
  LoginDTO:
    type: object
    required:
      - data
      - message
    properties:
      data:
        $ref: '#/definitions/LoginBody'
      message:
        type: string
        example: success
        description: success
  RingInfo:
    type: object
    required:
      - batter_power
      - firmware_update_flag
      - firmware_version
      - mode
      - provision_status
      - ring_name
      - ring_sn
    properties:
      ring_name:
        type: string
        description: 手環名稱
      ring_sn:
        type: string
        description: 手環序號
      firmware_version:
        type: string
        description: 手環韌體版本
      firmware_update_flag:
        type: integer
        format: int32
        description: 手環韌體更新
        enum:
          - 0
          - 1
      batter_power:
        type: integer
        format: int32
        description: 手環電量
        enum:
          - 5
          - 25
          - 50
          - 75
          - 100
      provision_status:
        type: string
        example: activated
        description: 手環開通狀態
        enum:
          - error(0)
          - provisioning(1)
          - activated(2)
      mode:
        type: string
        example: normal
        description: 手環當前模式
        enum:
          - normal(0)
          - fence(1)
          - active(2)
          - real-time(3)
  RingInfoDTO:
    type: object
    required:
      - data
      - message
    properties:
      data:
        $ref: '#/definitions/RingInfoBody'
      message:
        type: string
        example: success
        description: success
